version: '3.1'

services:
  oracle:
    image: oracleinanutshell/oracle-xe-11g
    container_name: oracle-xe-11g
    ports:
      - "1521:1521"
      - "8080:8080"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
    volumes:
      - oracle-data:/u01/app/oracle

volumes:
  oracle-data:
    driver: local

